packages:
  - apps/*

catalog:
  "@modelcontextprotocol/client": ^2.0.0
  "@modelcontextprotocol/express": ^2.0.0
  "@modelcontextprotocol/node": ^2.0.0
  "@modelcontextprotocol/server": ^2.0.0
  typescript: ^5.9.3
  zod: 4.5.4
